import Anthropic from "@anthropic-ai/sdk";
import type { SkillBundle } from "@/lib/skill/schema";

/** An LLM call: (systemPrompt, userMessage) → raw text response. */
export type LLM = (system: string, user: string) => Promise<string>;

const DEFAULT_MODEL = "claude-haiku-4-5-20251001";
const MAX_TOKENS = 3000;

/**
 * Choose the extraction backend:
 *  - a real Anthropic call when ANTHROPIC_API_KEY is set;
 *  - a deterministic offline mock otherwise, but ONLY when not in production.
 *    The mock lets UI development and the 50-parallel concurrency test run
 *    without burning tokens, and it derives its output from the input so each
 *    concurrent request gets a distinct, verifiable model.
 */
export function createLLM(skill: SkillBundle): LLM {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (apiKey) return realLLM(apiKey);
  if (process.env.NODE_ENV === "production") {
    throw new Error("ANTHROPIC_API_KEY is required in production");
  }
  return mockLLM(skill);
}

function realLLM(apiKey: string): LLM {
  const client = new Anthropic({ apiKey });
  const model = process.env.ANTHROPIC_MODEL || DEFAULT_MODEL;
  return async (system, user) => {
    const res = await client.messages.create({
      model,
      max_tokens: MAX_TOKENS,
      temperature: 0,
      system,
      messages: [{ role: "user", content: user }],
    });
    return res.content
      .filter((b): b is Anthropic.TextBlock => b.type === "text")
      .map((b) => b.text)
      .join("");
  };
}

/** Deterministic, input-derived mock (dev/test only). */
export function mockLLM(skill: SkillBundle): LLM {
  return async (_system, user) => {
    const text = (user.match(/<process>\n([\s\S]*?)\n<\/process>/)?.[1] ?? user).trim();
    const pieces = text
      .split(/[\n.;]+/)
      .map((s) => s.trim())
      .filter(Boolean);
    const processName = (pieces[0] || "Sample Process").slice(0, 50);
    const stepSource = pieces.slice(0, Math.min(6, skill.modeling.caps.maxTasks));
    const tasks =
      stepSource.length > 0
        ? stepSource.map((line, i) => ({
            id: `T${i + 1}`,
            name: line.slice(0, skill.modeling.labels.maxLabelChars),
            lane: "Team",
            system: null,
            document: null,
            next: i < stepSource.length - 1 ? `T${i + 2}` : null,
          }))
        : [
            {
              id: "T1",
              name: "Complete the process",
              lane: "Team",
              system: null,
              document: null,
              next: null,
            },
          ];
    const model = {
      processName,
      orgUnit: null,
      startEvent: "Start",
      lanes: ["Team"],
      tasks,
      decisions: [],
      endEvents: [
        { id: "E1", name: "Done", lane: "Team", from: tasks[tasks.length - 1].id },
      ],
      notes: ["Generated by the offline mock extractor (no ANTHROPIC_API_KEY set)."],
    };
    return JSON.stringify(model);
  };
}
